#!/bin/bash
# scripts/install/tmux.sh — install tmux and write sensible config
set -euo pipefail

source "$(dirname "$0")/../detect.sh"

install_tmux() {
  echo "── Installing tmux on ${OS_TYPE} ──"

  if command -v tmux &>/dev/null; then
    echo "✓ tmux already installed: $(tmux -V)"
    return
  fi

  case "$OS_TYPE" in
    linux)  sudo apt-get install -y tmux ;;
    mac)    brew install tmux ;;
    termux) pkg install tmux -y ;;
  esac

  echo "✓ tmux installed: $(tmux -V)"
}

write_tmux_config() {
  echo "── Writing tmux config ──"
  local conf="$HOME/.tmux.conf"

  # Skip if our config is already in place (idempotent)
  if [[ -f "$conf" ]] && grep -q "# Generated by tenai-infra" "$conf"; then
    echo "✓ tmux config already in place"
    return
  fi

  # Backup existing (only if it's not ours)
  [[ -f "$conf" ]] && cp "$conf" "${conf}.bak.$(date +%s)"

  cat > "$conf" << 'TMUXCONF'
# Generated by tenai-infra — re-run: make install-tmux
# ── Prefix ────────────────────────────────────────────────────────────────────
# Standard C-b prefix on all devices (consistent across mobile/desktop/server)
set -g prefix C-b
bind C-b send-prefix

# ── Mouse support ──────────────────────────────────────────────────────────────
set -g mouse on

# ── Session & window indexing ──────────────────────────────────────────────────
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# ── History ────────────────────────────────────────────────────────────────────
set -g history-limit 50000

# ── Terminal colors ────────────────────────────────────────────────────────────
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# ── Status bar ─────────────────────────────────────────────────────────────────
set -g status-interval 5
set -g status-left-length 40
set -g status-left "#[fg=green]#S #[fg=yellow]#I:#P "
set -g status-right "#[fg=cyan]%H:%M %d-%b #[fg=green]#H"
set -g status-style "bg=colour235,fg=colour136"

# ── Splits with intuitive keys ─────────────────────────────────────────────────
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# ── Pane navigation (vim-style) ────────────────────────────────────────────────
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ── Quick reload config ────────────────────────────────────────────────────────
bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

# ── Quick session switching ────────────────────────────────────────────────────
bind s choose-session

# ── Detach shortcut ────────────────────────────────────────────────────────────
bind d detach

# ── New window in current path ─────────────────────────────────────────────────
bind c new-window -c "#{pane_current_path}"

# ── Activity alerts ────────────────────────────────────────────────────────────
setw -g monitor-activity on
set -g visual-activity off
TMUXCONF

  echo "✓ tmux config written to $conf"
}

install_tmux
write_tmux_config
