#!/bin/bash
# scripts/configure/ssh.sh — write ~/.ssh/config entries for tailnet devices
# Reads device config from config/defaults.yaml and generates SSH Host entries
# dynamically. No hardcoded device names.
set -euo pipefail

source "$(dirname "$0")/../detect.sh"
source "$(dirname "$0")/../lib/state_track.sh"

INFRA_DIR="${INFRA_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
CONFIG_DIR="${CONFIG_DIR:-${INFRA_DIR}/config}"
PYTHON="${PYTHON:-${INFRA_DIR}/.venv/bin/python3}"
[[ -x "$PYTHON" ]] || PYTHON="$(command -v python3)"

# Read SSH key name from merged config (defaults.yaml + local.yaml overlay)
_ssh_key_name=$("$PYTHON" -c "
import sys; sys.path.insert(0, '$INFRA_DIR')
from scripts.lib.load_config import load_config
c = load_config()
print(c.get('ssh', {}).get('key_name', 'tenai-ssh-key'))
" 2>/dev/null || echo "tenai-ssh-key")

SSH_KEY="${SSH_KEY_PATH:-$HOME/.ssh/${_ssh_key_name}}"
SSH_KEY="${SSH_KEY/#\~/$HOME}"

SSH_CONFIG="$HOME/.ssh/config"

generate_ssh_key() {
  if [[ ! -f "$SSH_KEY" ]]; then
    echo "── Generating SSH key ──"
    mkdir -p "$HOME/.ssh"
    chmod 700 "$HOME/.ssh"
    ssh-keygen -t ed25519 -C "tenai-infra-$(hostname)" -f "$SSH_KEY" -N ""
    echo "✓ SSH key generated: $SSH_KEY"
    tenai_track ssh_key_created --path "~/.ssh/${SSH_KEY##*/}"
    echo "Public key:"
    cat "${SSH_KEY}.pub"
  else
    echo "✓ SSH key exists: $SSH_KEY"
  fi
}

write_ssh_config() {
  echo "── Writing SSH config ──"

  mkdir -p "$HOME/.ssh"
  touch "$SSH_CONFIG"
  chmod 600 "$SSH_CONFIG"

  local marker_start="# ── TENAI INFRA SSH START ──"
  local marker_end="# ── TENAI INFRA SSH END ──"

  # Remove old block
  if grep -q "$marker_start" "$SSH_CONFIG" 2>/dev/null; then
    "$PYTHON" - "$SSH_CONFIG" "$marker_start" "$marker_end" << 'PYEOF'
import sys
path, start, end = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path) as f:
    lines = f.readlines()
in_block = False
out = []
for line in lines:
    if start in line:
        in_block = True
    if not in_block:
        out.append(line)
    if end in line:
        in_block = False
with open(path, 'w') as f:
    f.writelines(out)
PYEOF
  fi

  # Generate Host entries dynamically from merged config (defaults.yaml + local.yaml)
  local host_entries
  host_entries=$("$PYTHON" - "$INFRA_DIR" "$SSH_KEY" << 'PYEOF'
import sys, os
infra_dir = sys.argv[1]
sys.path.insert(0, infra_dir)
from scripts.lib.load_config import load_config
ssh_key = sys.argv[2]
cfg = load_config()
devices = cfg.get("tailscale", {}).get("devices", {})
for name, dev in devices.items():
    ip = dev.get("ip", "")
    user = dev.get("user", "")
    dtype = dev.get("type", "server")
    ssh_port = dev.get("ssh_port", 22)
    if not ip or not user:
        continue
    print(f"Host {name}")
    print(f"    HostName {ip}")
    print(f"    User {user}")
    if ssh_port != 22:
        print(f"    Port {ssh_port}")
    print(f"    IdentityFile {ssh_key}")
    print(f"    StrictHostKeyChecking accept-new")
    if dtype not in ("android", "ios_ish"):
        print(f"    ServerAliveInterval 60")
        print(f"    ServerAliveCountMax 3")
    print()
PYEOF
  )

  cat >> "$SSH_CONFIG" << SSHCONF

${marker_start}
# Generated by tenai-infra — re-run: make configure-ssh

${host_entries}
# Shared defaults for all tailnet hosts
Host 100.* 
    StrictHostKeyChecking accept-new
    ServerAliveInterval 60
    ServerAliveCountMax 3
    IdentityFile ${SSH_KEY}

${marker_end}
SSHCONF

  chmod 600 "$SSH_CONFIG"
  echo "✓ SSH config written to $SSH_CONFIG"
  tenai_track ssh_config_block \
    --marker-start "# ── TENAI INFRA SSH START ──" \
    --marker-end   "# ── TENAI INFRA SSH END ──"
}

copy_public_key_to_server() {
  local target="$1"
  local user="$2"
  local ip="$3"

  echo "── Copying public key to ${target} (${user}@${ip}) ──"
  if ssh-copy-id -i "${SSH_KEY}.pub" -o StrictHostKeyChecking=accept-new "${user}@${ip}" 2>/dev/null; then
    echo "✓ Key copied to $target"
  else
    echo "Manual step — add this to ${target}:~/.ssh/authorized_keys:"
    cat "${SSH_KEY}.pub"
  fi
}

generate_ssh_key
write_ssh_config

# Optionally distribute key to all configured devices
if [[ "${DISTRIBUTE_SSH_KEY:-false}" == "true" ]]; then
  "$PYTHON" - "$CONFIG_DIR" << 'PYEOF' | while IFS='|' read -r name user ip; do
import sys, yaml, os
config_dir = sys.argv[1]
cfg_path = os.path.join(config_dir, "defaults.yaml")
if not os.path.exists(cfg_path):
    sys.exit(0)
with open(cfg_path) as f:
    cfg = yaml.safe_load(f) or {}
devices = cfg.get("tailscale", {}).get("devices", {})
for name, dev in devices.items():
    ip = dev.get("ip", "")
    user = dev.get("user", "")
    if ip and user:
        print(f"{name}|{user}|{ip}")
PYEOF
    copy_public_key_to_server "$name" "$user" "$ip"
  done
fi
