#!/bin/bash
# scripts/conductor/gemini_session.sh
# Start or attach a Gemini CLI Conductor session for a repository.
# Each repo gets its own tmux session: <repo-name>-conductor
#
# Usage:
#   REPO_DIR=/path/to/repo bash gemini_session.sh          # start conductor
#   REPO_DIR=/path/to/repo ACTION=attach bash ...          # attach existing
#   REPO_DIR=/path/to/repo ACTION=kill bash ...            # kill session
#   REPO_DIR=/path/to/repo ACTION=tasks bash ...           # show TASKS.md
#
# Requires: gemini (npm -g @google/gemini-cli), tmux

set -euo pipefail
source "$(dirname "$0")/../detect.sh"

# ── Args ─────────────────────────────────────────────────────────────────────
REPO_DIR="${REPO_DIR:-$(pwd)}"
ACTION="${ACTION:-start}"
TASKS_FILE="${TASKS_FILE:-}"
NO_ATTACH="${NO_ATTACH:-}"
NEW_SESSION="${NEW_SESSION:-}"

# Read conductor config from merged config (defaults + local)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
_LOADER="${SCRIPT_DIR}/../lib/load_config.py"
if [[ -f "$_LOADER" ]] && [[ -n "${PYTHON:-}" ]] && [[ -x "$PYTHON" ]]; then
  _cfg_model=$($PYTHON "$_LOADER" --get conductor.gemini_model 2>/dev/null || echo "")
  _cfg_tasks=$($PYTHON "$_LOADER" --get conductor.task_output_file 2>/dev/null || echo "")
  _cfg_split=$($PYTHON "$_LOADER" --get conductor.split_pane 2>/dev/null || echo "false")
  [[ -n "$_cfg_model" ]] && : "${GEMINI_MODEL:=$_cfg_model}"
  [[ -n "$_cfg_tasks" ]] && : "${TASKS_FILE:=$_cfg_tasks}"
  [[ -n "$_cfg_split" ]] && : "${SPLIT_PANE:=$_cfg_split}"
fi
GEMINI_MODEL="${GEMINI_MODEL:-gemini-2.5-pro}"
TASKS_FILE="${TASKS_FILE:-TASKS.md}"
SPLIT_PANE="${SPLIT_PANE:-false}"

# Read launch_args from config/cli/gemini.yaml
_cli_launch_args() {
  local cfg="${SCRIPT_DIR}/../../config/cli/gemini.yaml"
  if [[ -f "$cfg" ]] && [[ -n "${PYTHON:-}" ]] && [[ -x "$PYTHON" ]]; then
    $PYTHON -c "import yaml; args=yaml.safe_load(open('$cfg')).get('launch_args',[]); print(' '.join(args))" 2>/dev/null || echo ""
  fi
}
GEMINI_CLI_ARGS=$(_cli_launch_args)

REPO_NAME="$(basename "$REPO_DIR")"
SESSION_BASE="${REPO_NAME}-conductor"
SESSION="$SESSION_BASE"

# NEW_SESSION=1 → find next available numbered suffix (-1, -2, etc.)
if [[ "$NEW_SESSION" == "1" ]]; then
  n=1
  while tmux has-session -t "${SESSION_BASE}-${n}" 2>/dev/null; do
    n=$((n + 1))
  done
  SESSION="${SESSION_BASE}-${n}"
fi

# ── Helpers ──────────────────────────────────────────────────────────────────
session_exists() {
  tmux has-session -t "$SESSION" 2>/dev/null
}

# Count how many conductor sessions exist for this repo
count_sessions() {
  tmux list-sessions -F '#{session_name}' 2>/dev/null | grep -c "^${SESSION_BASE}" || echo 0
}

ensure_gemini_md() {
  if [[ ! -f "${REPO_DIR}/GEMINI.md" ]]; then
    echo "⚠  No GEMINI.md found — generating template..."
    bash "$(dirname "$0")/../configure/gemini_md.sh"
  fi
}

ensure_tasks_md() {
  if [[ ! -f "${REPO_DIR}/${TASKS_FILE}" ]]; then
    cat > "${REPO_DIR}/${TASKS_FILE}" << 'TMPL'
# TASKS.md — Agent Task Backlog
# Generated by Gemini Conductor. Each task must pass the ATC filter:
# Self-Contained | Verifiable | Bounded | Parallelizable | Resume-safe

## Active
<!-- Gemini will populate this section -->

## In Progress
<!-- Move tasks here when dispatching to an agent worktree -->

## Done
<!-- Completed tasks -->
TMPL
    echo "✓ TASKS.md created"
  fi
}

# ── Actions ──────────────────────────────────────────────────────────────────
start_conductor() {
  ensure_gemini_md
  ensure_tasks_md

  if session_exists; then
    echo "✓ Session '${SESSION}' already running — attaching"
    tmux attach-session -t "$SESSION"
    return
  fi

  echo "── Starting Gemini Conductor for: ${REPO_NAME} ──"
  echo "   Session: ${SESSION}"
  echo "   Model:   ${GEMINI_MODEL}"
  echo "   Dir:     ${REPO_DIR}"

  # Create the session first — this starts the tmux server if it's not running
  # Use tput for size when available, fall back to generous defaults for SSH
  local _cols _rows
  _cols=$(tput cols 2>/dev/null || echo 200)
  _rows=$(tput lines 2>/dev/null || echo 50)
  tmux new-session -d -s "$SESSION" -c "$REPO_DIR" -x "$_cols" -y "$_rows"
  sleep 0.2  # let tmux initialize the session

  # Prevent tmux from killing session when last client detaches
  tmux set-option -t "$SESSION" destroy-unattached off 2>/dev/null || true

  # Detect tmux base indices AFTER session creation (server must be running)
  # Note: must use || true because pipefail propagates tmux's non-zero exit
  local win_base pane_base
  win_base=$(tmux show-options -g base-index 2>/dev/null | awk '{print $2}' || true)
  pane_base=$(tmux show-options -g pane-base-index 2>/dev/null | awk '{print $2}' || true)
  win_base="${win_base:-0}"
  pane_base="${pane_base:-0}"
  local W="${SESSION}:${win_base}"
  local P0="${W}.${pane_base}"
  local P1="${W}.$((pane_base + 1))"

  # Rename window
  tmux rename-window -t "$W" "conductor"

  # Try to split vertically: right pane for task monitor (optional, disabled by default)
  # Enable via config: conductor.split_pane: true  or  SPLIT_PANE=true
  local _split_ok=false
  if [[ "$SPLIT_PANE" == "true" ]]; then
    if tmux split-window -t "$W" -h -p 32 -c "$REPO_DIR" 2>/dev/null; then
      _split_ok=true
      # Right pane: live task watcher
      tmux send-keys -t "$P1" \
        "watch -n 3 'echo \"=== TASKS ===\"; cat ${TASKS_FILE} 2>/dev/null; echo; echo \"=== GIT ===\"; git status --short; echo; echo \"=== WORKTREES ===\"; git worktree list'" \
        Enter
    fi
  fi

  # Main pane: Gemini Conductor (always runs, even if split failed)
  # Conductor workflow: spec → plan → implement
  # The GEMINI.md instructs Gemini to output tasks to TASKS.md
  CONDUCTOR_PROMPT="You are the Conductor for project ${REPO_NAME}. Read GEMINI.md for instructions. Your task is to analyze the codebase, then populate ${TASKS_FILE} with a prioritized backlog of ATC-passing tasks (Self-Contained, Verifiable, Bounded, Parallelizable, Resume-safe) for Claude Code agents to implement in parallel git worktrees. Start with: 1) spec - analyze the codebase, 2) plan - decompose into tasks, 3) write tasks to ${TASKS_FILE}."

  tmux send-keys -t "$P0" \
    "cd ${REPO_DIR} && echo '── Gemini Conductor starting for ${REPO_NAME} ──' && gemini ${GEMINI_CLI_ARGS} --model ${GEMINI_MODEL}" \
    Enter

  # Focus on left pane (only if split succeeded)
  if [[ "$_split_ok" == "true" ]]; then
    tmux select-pane -t "$P0"
  fi

  echo "✓ Conductor session '${SESSION}' started"
  echo ""
  echo "Attach:  tmux attach -t ${SESSION}"
  echo "Send:    tmux send-keys -t ${P0} '<prompt>' Enter"
  echo "Kill:    tmux kill-session -t ${SESSION}"
  echo ""

  # Auto-attach if running interactively and not explicitly told not to
  if [[ -z "$NO_ATTACH" && -t 0 ]]; then
    tmux attach-session -t "$SESSION"
  fi
}

attach_conductor() {
  if session_exists; then
    tmux attach-session -t "$SESSION"
  else
    echo "No conductor session for '${REPO_NAME}'. Start with: ACTION=start"
    exit 1
  fi
}

kill_conductor() {
  if session_exists; then
    tmux kill-session -t "$SESSION"
    echo "✓ Killed session: ${SESSION}"
  else
    echo "No active session: ${SESSION}"
  fi
}

show_tasks() {
  local tasks_path="${REPO_DIR}/${TASKS_FILE}"
  if [[ -f "$tasks_path" ]]; then
    echo "═══ TASKS: ${REPO_NAME} ═══"
    cat "$tasks_path"
  else
    echo "No ${TASKS_FILE} found in ${REPO_DIR}"
  fi
}

send_prompt() {
  # Send a prompt to the running Gemini Conductor pane
  local prompt="${PROMPT:-}"
  if [[ -z "$prompt" ]]; then
    echo "Usage: PROMPT='generate tasks for auth module' ACTION=send bash gemini_session.sh"
    exit 1
  fi
  if session_exists; then
    local win_base pane_base
    win_base=$(tmux show-options -g base-index 2>/dev/null | awk '{print $2}' || true)
    pane_base=$(tmux show-options -g pane-base-index 2>/dev/null | awk '{print $2}' || true)
    win_base="${win_base:-0}"
    pane_base="${pane_base:-0}"
    tmux send-keys -t "${SESSION}:${win_base}.${pane_base}" "$prompt" Enter
    echo "✓ Sent prompt to ${SESSION}"
  else
    echo "Session ${SESSION} not running. Start first."
    exit 1
  fi
}

list_all_sessions() {
  echo "── Active conductor sessions ──"
  local sessions
  sessions=$(tmux list-sessions -F '#{session_name}: #{session_windows} windows (created #{session_created_string})' 2>/dev/null | grep "\-conductor" || true)
  if [[ -z "$sessions" ]]; then
    echo "(none)"
    return
  fi
  # Group by repo name (everything before -conductor)
  local prev_repo=""
  echo "$sessions" | sort | while IFS= read -r line; do
    local sname="${line%%:*}"
    # Extract repo name: remove -conductor suffix and any -N suffix
    local repo
    repo=$(echo "$sname" | sed 's/-conductor\(-[0-9]*\)\{0,1\}$//')
    if [[ "$repo" != "$prev_repo" ]]; then
      [[ -n "$prev_repo" ]] && echo ""
      echo "  📁 $repo"
      prev_repo="$repo"
    fi
    echo "    └ $line"
  done
}

# ── Dispatch ─────────────────────────────────────────────────────────────────
case "$ACTION" in
  start)   start_conductor ;;
  attach)  attach_conductor ;;
  kill)    kill_conductor ;;
  tasks)   show_tasks ;;
  send)    send_prompt ;;
  list)    list_all_sessions ;;
  *)
    echo "Unknown action: $ACTION"
    echo "Valid: start | attach | kill | tasks | send | list"
    exit 1
    ;;
esac
